version: '3.9'

services:

  db:
    image: mysql:8
    container_name: pro_dev_db
    restart: always
    environment:
      MYSQL_DATABASE: "pro_dev"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  db_data:
